### ISSUE TITLE
Cmdr doesn't register more new custom commands than 10??

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [evaera/Cmdr#117]
So if I already have 10 custom commands, I can't register new commands anymore.

I do not know wether this was a intended behaviour or not, but reducing the amount of commands fixes this problem.

**Comment by RealEthanPlayzDev** [comment]
(I am sorry if my english is bad also)

**Comment by evaera** [comment]
You need to provide a limited reproduction for me to help you, otherwise this report is unactionable. Will reopen if an issue is discovered.
