### ISSUE TITLE
Gui should not be instantiated in StarterGui

### ISSUE THREAD

**Issue by Validark** [evaera/Cmdr#12]
There are a number of problems with this. For one, it gives a copy to everyone by default. Furthermore, if this code runs after any players have already joined, then it will not be replicated to them. Instead, authorized players who should be able to use Cmdr should call the instantiation function on their machines.

**Comment by evaera** [comment]
I will add a special condition to manually clone it from the StarterGui from the Client, but the other points are actually intended behavior.

The GUI is only created if it doesn't already exist, this mirrors how all of the default Roblox GUIs work. This lets users change the color scheme if they wanted to for example.

And if the game developer wants to disallow players from seeing Cmdr, there is a special API call for this-- `CmdrClient:SetEnabled(false)`.

There is no concept of "Authorized players" in the way that you are speaking of here in Cmdr, as there are only command hooks which may interrupt the commands at run time for a variety of factors.

Good shout on the replication bit, though 👍
