### ISSUE TITLE
Don't allow execution in non-Studio if no BeforeRun hook is setup

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#120]
As a security precaution

**Comment by TsjipTsjip** [comment]
This has no 'help wanted' tag on it. Would you mind if I give this a try anyway?

**Comment by evaera** [comment]
go ahead!

**Comment by TsjipTsjip** [comment]
Thanks! I'll try not to mess up the formatting this time.

**Comment by TsjipTsjip** [comment]
#132

**Comment by enescglyn** [comment]
#132 is merged, this should be closed.
