### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#121]
- `list [something]`: 
  - `players`
- `pick [n] [list]`: Get a value from a list
- `len [list]`: Length of list
- `random [n]`: Get a random value between 1..n

Get a random player:
`pick ${run random ${len list players}} ${list players}`

Maybe: `pick !random [list]` as a built-in to pick from a list

**Comment by TheNexusAvenger** [comment]
For my use case (Innovation Security's use case), trainers run commands on random players for specific rounds in the game (ex: `:bring random,random,random` to bring 3 random players, oh say to be snipers). Moving to Cmdr currently means the functionality doesn't exist. It would be helpful to have "random" being valid for the `player` and `players` type.
