### ISSUE TITLE
No method to see what version of cmdr that is included in the project

### ISSUE THREAD

**Issue by robinwassen** [evaera/Cmdr#123]
As a developer there is no way to see what version of cmdr that is installed in a project if it has been installed with the "manual" method.

**Two options to solve this issue are:**
- Include the version in a comment in the cmdr source file
- Include the version in the help command or provide a version command

The problematic thing with such a feature would be that it has to be maintained or integrated into the CI / release process if automated.

**Current workaround:** Check if the changes from a commit is included in the installed cmdr to determine the version number.

**Comment by evaera** [comment]
I can see how this is an issue but I am not sure if it is a Cmdr issue. Maybe you should consider installing via a Git submodule instead?

**Comment by robinwassen** [comment]
@evaera Not everyone are using rojo / RoStrap.

**Comment by robinwassen** [comment]
It is kind of a ticket to be able to help you better, if you get a bug report the chance that you get the correct affected version increases. :)

**Comment by robinwassen** [comment]
I would like to emphasize, if you do not think it's worth spending time on. Feel free to close it, it is your project and you decide :)

And thanks for building this - so much better than building custom admin UI's n stuff like we did for our first game.
