### ISSUE TITLE
The cmdr input field is selectable using controller when GUI is not visible

### ISSUE THREAD

**Issue by robinwassen** [evaera/Cmdr#124]
Cmdr is interfering with the selection cursor when playing with a controller.

**Affected versions:** 1.5.0, 1.4.0

**Steps to reproduce:**
- Play with a controller
- Press the back button to toggle the GUI selection 

**Expected results:** You should not be able to select the input field

**Actual results:** The cmdr input field is selectable

**Prosposed solution:**
- Add a selection group to the cmdr frame

![image](https://user-images.githubusercontent.com/302151/81140353-4f1f2280-8f69-11ea-8e83-4d05aa6e6a8d.png)

**Comment by evaera** [comment]
We can fix this by setting [https://developer.roblox.com/en-us/api-reference/property/GuiObject/Selectable] to false in https://github.com/evaera/Cmdr/blob/master/Cmdr/CreateGui.lua

**Comment by robinwassen** [comment]
@evaera I will get back with a PR in 15 minutes to fix this :)
