### ISSUE TITLE
Tab autocomplete always returns the first entry

### ISSUE THREAD

**Issue by benal20** [evaera/Cmdr#142]
When using the tab key to autocomplete an argument in CMDR, CMDR will always autofill the topmost response, even if you have used the arrow keys to select a different entry. 

As an example, if you start typing "add," move the cursor down to "additem," and press the TAB key, CMDR will autofill "addallitems" because it appears first alphabetically. This occurs for every autofill instance where there is more than one option.

GIF of this happening from Nat: https://i.imgur.com/1z4IB3R.gif
Reproduced by Nat and Ben as of the summer sale update.

**Comment by DevKurka** [comment]
Noticed the same issue.

**Comment by evaera** [comment]
I don't think this happens anymore.. can anyone confirm?

**Comment by evaera** [comment]
Confirmed fixed
