### ISSUE TITLE
Make CommandDefinition "Description" value optional

### ISSUE THREAD

**Issue by jackTabsCode** [evaera/Cmdr#146]
Often times I do not find myself needing to add a description to a command definition. Allow "Definition" to be optional, and if not present, do not display the definition text (and cut down on the space it uses).

**Comment by wilyt1** [comment]
The Description frame is already hidden when there is no description.

https://github.com/evaera/Cmdr/blob/28564bb373d7438b087de1eea0c33d5de8fc65d3/Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua#L23-L30

https://github.com/evaera/Cmdr/blob/28564bb373d7438b087de1eea0c33d5de8fc65d3/Cmdr/CmdrClient/CmdrInterface/AutoComplete.lua#L37

**Comment by autonordev** [comment]
Description is already optional, however:

1. the CommandContext api reference says that it's not
2. the help command will simply display `nil` in place of a description
