### ISSUE TITLE
`ValidateOnce` does not work on types created with `Util.MakeListableType`

### ISSUE THREAD

**Issue by finobinos** [evaera/Cmdr#202]
Currently, `Validate` works on both listable and non-listable types. However, `ValidateOnce` only works on non-listable types. 

## Repro

- To quickly reproduce this bug, firstly use the `playerIds` type (listable) on some command, as it has a `ValidateOnce` function to check if the given user id is valid.
- Pass in an invalid user id and run the command (press enter). 
- You should see no validation checks, because `ValidateOnce` is not called and the command will successfully run.

Switch the command to use the `playerId` type (singular) and you should see it validate invalid user ids.

**Comment by evaera** [comment]
Feel free to make a PR 
https://github.com/evaera/Cmdr/blob/master/Cmdr/Shared/Util.lua#L280

**Comment by finobinos** [comment]
> Feel free to make a PR https://github.com/evaera/Cmdr/blob/master/Cmdr/Shared/Util.lua#L280

https://github.com/evaera/Cmdr/pull/203
