### ISSUE TITLE
Ability to make `context:Reply` calls print to chat

### ISSUE THREAD

**Issue by LewisTehMinerz** [evaera/Cmdr#204]
I currently have the following script that runs after Cmdr is initialised on the client:
```lua
function playerChatted(msg)
	if msg:sub(1, 1) == "-" then
		local response = Cmdr.Dispatcher:EvaluateAndRun(Cmdr.Util.RunEmbeddedCommands(Cmdr.Dispatcher, msg:sub(2)))
		StarterGui:SetCore("ChatMakeSystemMessage", {
			Text = response,
			Color = Color3.fromRGB(0, 255, 215)
		})
	end
end

game:GetService("Players").LocalPlayer.Chatted:Connect(playerChatted)
```
(I've based this off of the `bind` command, so sorry if this is the incorrect way of doing things! 😅)

If I run `help`, for instance, because all of the messages are sent through `context:Reply` calls, I have no way of getting the response and printing it to the chat, meaning the end user would have to open the console to see the output, thus defeating the point of chat commands in the first place.

I need these as a convenience mechanism so players and admins alike don't have to open the console to run various commands. Is there any way of doing so or is this something I will just have to deal with and patch in myself?

**Comment by evaera** [comment]
You can already do this by overriding the network event handler for AddLine from the client.

```lua
Cmdr:HandleEvent("AddLine", function (...)
		Window:AddLine(...)
	end)
```
