### ISSUE TITLE
Up/down arrow should traverse command history when no text has been entered

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#21]

**Comment by TripleFrequency** [comment]
How do you feel about storing a player's command history as a `TeleportService` setting, @evaera? It wouldn't be full persistence, but it would certainly be convenient.

With history, perhaps we could make it so you have to explicitly enable it, so something like
`Cmdr:SetHistoryEnabled(isEnabled: boolean, autoPersist?: boolean)`
on the client.
