### ISSUE TITLE
context:Reply() is not doing \n right 

### ISSUE THREAD

**Issue by LawMixer** [evaera/Cmdr#217]
On my prints, it's how I want it, but on the actual Gui itself, it's not reproducing it the same way. I'll provide a screenshot below and it'll give a bit better example of what's going on;

https://i.imgur.com/48uxd6M.png

Code:
```lua
local function readModerationHistory(context, profile, modHistory)
	for i, modHistory in pairs(modHistory) do
		for i, v in pairs(modHistory) do
			--print("``"..v.CaseId.."``\n\n".."Date: "..v.Date.."\n".."ModType: "..v.ModType.."\n".."Moderator:"..v.Moderator.."\n".."Reason: "..v.Reason)
			context:Reply("``"..v.CaseId.."``\n\n".."Date: "..v.Date.."\n".."ModType: "..v.ModType.."\n".."Moderator: "..v.Moderator.."Reason: "..v.Reason)
		end

	end
end
```

**Comment by wilyt1** [comment]
There is a discrepancy between the string passed to print statement and the text passed to `CommandContext:Reply()`.

**Comment by LawMixer** [comment]
Alright, how would I fix that?

**Comment by wilyt1** [comment]
You are not passing the same thing to each of them.

**Comment by LawMixer** [comment]
Whoops, my bad! Didn't see the error, thanks will.
