### ISSUE TITLE
Cmdr Client Infinitely Hangs

### ISSUE THREAD

**Issue by sasial-dev** [evaera/Cmdr#229]
## Original Debugging

Original Debugging on this problem was done in the roblox-ts server at [this URL](https://discord.com/channels/476080952636997633/1006833758361616415/1008145760027693056).

## What has been determined
This is not an issue with the roblox-ts port (same code, just with typing files) of cmdr.

## What actually happens
1. Importing gets stuck in an infinite loop due to custom types importing Cmdr
2. Custom Commands do not register, as they require the custom types
3. Help Command does not register
<img width="1137" alt="RobloxStudio-cxBzhhZk" src="https://user-images.githubusercontent.com/44125644/185768999-fe61a533-6721-4903-af37-d3e44eafff9c.png">

## Minimal Repro
https://github.com/Tourville-Technologies/cmdr-repro

**Comment by sasial-dev** [comment]
Attached is a rbxl file so you don't have to compile the TypeScript:
(apologies, GitHub only supports .zip not .rbxl)
[cmdr-repro.rbxl.zip](https://github.com/evaera/Cmdr/files/9388158/cmdr-repro.rbxl.zip)

**Comment by evaera** [comment]
This is not correct usage. You cannot have circular dependencies in your code, this is not an issue related to Cmdr. If you need to access Cmdr inside a type definition, you can access it via `registry.Cmdr`

**Comment by sasial-dev** [comment]
It is still an issue after removing the circular dep. I've pushed to the repo/see below:
[cmdr-repro-2.rbxl.zip](https://github.com/evaera/Cmdr/files/9388166/cmdr-repro-2.rbxl.zip)
ndency.

**Comment by evaera** [comment]
There isn't any problem with the library here. I was able to download your game, fix the circular dependencies and it loaded fine. I think you might be incorrectly importing Cmdr on the client, but I don't really know how roblox-ts expects the library to work.

**Comment by sasial-dev** [comment]
roblox-ts imports it correctly, I believe?

https://github.com/osyrisrblx/Cmdr/blob/ts/TS/init.lua

**Comment by evaera** [comment]
Looks correct, however I was still able to load your game by fixing the circular dependencies and changing the import in the client module, so this is definitely an issue on your end.
