### ISSUE TITLE
RegisterCommandsIn does not listen for new descendants, resulting in a race condition

### ISSUE THREAD

**Issue by Hexcede** [evaera/Cmdr#241]
When registering commands, RegisterCommandsIn does not use DescendantAdded or ChildAdded. This results in a race condition, even when used on static server-side code, or using Cmdr's setup guide. This is especially pronounced in games with many instances statically present. RegisterCommandsIn should likely listen for new command modules to be added and should load them.

Additionally, small critique, but RegisterCommandsIn uses recursion, but GetDescendants would (probably?) be sufficient and likely would read a bit cleaner. This changes behaviour for commands that have modules inside of them, but I don't think that is great, any shared code should probably exist in a separate location.

**Comment by Hexcede** [comment]
I will probably submit a PR for this stuff later tonight if I have the time.

**Comment by evaera** [comment]
I'm not interested in accepting a PR for this change. There is no possibility for a race condition with the current implementation. Roblox games do not begin executing code until all Instances that are in the DataModel when loading began have been loaded, unless your script is inside ReplicatedFirst. If you insert scripts or ModuleScripts manually after the game is loaded, then you should delay calling `RegisterCommandsIn` until you've finished doing so. I see no reason to change an API that has been stable for nearly five years now for something that can only happen if you are doing something strange.

Many users do actually have submodules inside of their command implementations and so we purposefully do not use `GetDescendants` here.

**Comment by Hexcede** [comment]
> There is no possibility for a race condition with the current implementation.

I experience race conditions consistently when there are a large number of instances. Nothing weird is being done.

**Comment by Hexcede** [comment]
@evaera As I said before, there's definitely a race condition going on, and we aren't doing anything weird. I have screenshots below of the structure, I have the code being used, etc. In this case, even the help command isn't registering, which is simply a built-in command. There are no errors nor warnings in the output.

![image](https://user-images.githubusercontent.com/8394472/217385911-d960f522-ee3d-4cf9-8fb0-84d9bd3b46e6.png)

![image](https://user-images.githubusercontent.com/8394472/217385980-df7016f5-3779-450f-9c36-1d9b9d42247d.png)
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Cmdr = require(ReplicatedStorage:WaitForChild("CmdrClient"))

Cmdr:SetActivationKeys({ Enum.KeyCode.F2 })
Cmdr:SetPlaceName("Tycoon Engine")
```

![image](https://user-images.githubusercontent.com/8394472/217386050-0901c497-238e-42fa-aa30-dbc8742bb3ee.png)
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Cmdr = require(ReplicatedStorage.Packages.Cmdr)

Cmdr:RegisterHooksIn(script.hooks)
Cmdr:RegisterDefaultCommands()
Cmdr:RegisterCommandsIn(script.commands)
```

At runtime the commands are present within CmdrClient but cannot be run:
![image](https://user-images.githubusercontent.com/8394472/217386209-cf6e2a71-d129-4ace-b1e8-37c6ad9e09d0.png)
![image](https://user-images.githubusercontent.com/8394472/217386229-bce09b58-f06b-4250-b9c2-cf4b4f3c8730.png)
![image](https://user-images.githubusercontent.com/8394472/217386305-6389e536-88da-4265-a9e0-f2438b0c7b69.png)
![image](https://user-images.githubusercontent.com/8394472/217386447-79cb937e-b8d5-4354-b744-f18967a36fa2.png)

Pre-runtime:
![image](https://user-images.githubusercontent.com/8394472/217386660-fe527ead-6ea7-47e0-ad89-63b68fb25b41.png)

**Comment by schmatz** [comment]
We are also experiencing this issue with the exact same symptoms, like `"help" is not a valid command name`. I manage to repro this in Studio but haven't managed to repro it in production. 

I suspect that this bug may stem from [this line](https://github.com/evaera/Cmdr/blob/28564bb373d7438b087de1eea0c33d5de8fc65d3/Cmdr/CmdrClient/init.lua#L112) which may need to be something like `RunService:IsStudio()` rather than `RunService:IsServer()`. I haven't tested that hypothesis though and am not familiar with the Cmdr initialization code. 

I've done timing experiments and the commands can take nearly a full second to replicate to the client Commands folder. If Cmdr is instantiated before the commands replicate, this race condition will be observed.

@Hexcede what workaround did you pursue? Waiting on the client for a few commands to replicate that we know will be present before initializing Cmdr seems to work for us.

**Comment by evaera** [comment]
It seems like it might be related to the `var` and `varSet` commands - try not loading those and see if it fixes

**Comment by schmatz** [comment]
I'll give it a shot and let you know if that helps. Thanks for looking into this!

**Comment by schmatz** [comment]
@evaera good find, deleting var/varSet commands seems to resolve the issue for us.
