### ISSUE TITLE
Autocomplete doesn't recognise word shorthands 

### ISSUE THREAD

**Issue by benhdev** [evaera/Cmdr#260]
Upon installing the latest version I have found that I can no longer use the shorthands "me", "all", or "others"

"random" would be nice too, but not sure that was even there in the first place.

Yes, I know I can use ".", "*" or "**" in place of these, however the old wording was much nicer and more memorable. I'd at least like the option to configure these myself, or just have both of the options available.

I have found these still in part of the AutoComplete of CmdrClient. However they are unusable. I had a quick look at resolving it myself but id probably have to do some serious digging and learning of the codebase for that.

`CmdrClient.CmdrInterface.AutoComplete line 13`
```lua
local Shorthands = Util.MakeDictionary({"me", "all", ".", "*", "others"})
```

**Comment by evaera** [comment]
Hi, these were intentionally removed with our revamp to allow shorthands to work for any type. Please see this in the docs here:

https://eryn.io/Cmdr/guide/Commands.html#argument-value-operators

It seems like the remaining "me", "all", and "others" in that file was an oversight and weren't completely removed when we made this change. It doesn't seem to be affecting anything, though.

**Comment by benhdev** [comment]
There should be a way to configure these shorthands, or at least keep the old ones available on arguments with a player type.
 
I use Cmdr for the moderation of one of my games and I can't use the new version there unless I change to allow these shorthands as it would be very confusing for the mods.

**Comment by evaera** [comment]
That's understandable. If you like, you could submit a PR that:

- Allows Types to specify word names for each shorthand operator within the Type struct (https://eryn.io/Cmdr/api/Registry.html#typedefinition)

Something like:

```lua
{
  ArgumentValueOperatorAliases = {
    me = ".",
    all = "*",
    others = "**",
    --etc
  }
}
```

- Check for that option in this code, and additionally check for the specified aliases (in addition to the regular operators) https://github.com/evaera/Cmdr/blob/master/Cmdr/Shared/Argument.lua#L74

maybe like this:
```lua
local operatorAlias = self.Type.ArgumentValueOperatorAliases[rawValue]
if operatorAlias then
  rawValue = operatorAlias
end
```

- Specify this option in the default `player` and `playerId` types and ensure it works
