### ISSUE TITLE
Can't open cmdr.

### ISSUE THREAD

**Issue by EvanDevvv** [evaera/Cmdr#287]
I have configured cmdr on server and client, and when clicking F2, nothing happens.

**Comment by NidhoRoblox** [comment]
did you follow the setup tutorial? are there any errors in the output?

**Comment by EvanDevvv** [comment]
> did you follow the setup tutorial? are there any errors in the output?

Yes, I did, I ended up just following a thing where it just opens via a button, there were no errors.
