### ISSUE TITLE
I followed a tutorial on how to make a Spawn Enemy Script on CMDR but this pops up

### ISSUE THREAD

**Issue by alextheape123** [evaera/Cmdr#297]
ServerScriptService.Cmdr.Shared.Registry:102: Unknown property in command "Spawn_Enemy" argument #1: type[](url)
 ^^Problem^^
 [](url)

**Comment by alextheape123** [comment]
its a tower defense game btw

**Comment by autonordev** [comment]
GitHub Issues is not for support requests. You should use our Discord server or another more appropriate place to get help with your code.
