### ISSUE TITLE
Make tab completion encapsulate entire argument in quotes, not just last segment

### ISSUE THREAD

**Issue by TripleFrequency** [evaera/Cmdr#36]
If you have a listable type, and attempt to use CSV with quotes, the values aren't found.

As a simple example using built-in types/commands:
This command would work: `teleport TripleFrequency,TripleFrequency TripleFrequency`
But this command wouldn't: `teleport "TripleFrequency",TripleFrequency TripleFrequency`

This is only an issue when specifying multiple values, if you only have one value of a listable type, then it still works: `teleport "TripleFrequency" TripleFrequency`

If any of values in a listable type are in quotes, then it fails.

**Comment by evaera** [comment]
Quotes need to go around the entire argument, the real problem here is the auto-completion working incorrectly.
