### ISSUE TITLE
RegisterDefaultCommands doesn't respect filter array

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#64]
Code:

Server:
```lua
local replicatedStorage = game:GetService('ReplicatedStorage')
local cmdr = require(replicatedStorage.Cmdr)

cmdr:RegisterDefaultCommands({'Help', 'DefaultUtil'})
```

Client:
```lua
local replicatedStorage = game:GetService('ReplicatedStorage')
local cmdr = require(replicatedStorage:WaitForChild('CmdrClient'))

cmdr:SetPlaceName('[censored]')
cmdr:SetMashToEnable(true)
cmdr:SetActivationKeys({Enum.KeyCode.Semicolon})
```

Result:

![image](https://user-images.githubusercontent.com/4723091/52908840-b6509a00-3232-11e9-94ab-6349167418d3.png)

You sure this is only help and util?

I installed it with RoStrap, I'll try manually installing it from the repo and see if the issue's fixed.

**Comment by LoganDark** [comment]
Manual install has the same issue.

**Comment by evaera** [comment]
Thanks for the report, I'm investing the issue now

**Comment by LoganDark** [comment]
Passing a function does filter as expected

**Comment by LoganDark** [comment]
Thank you!
