### ISSUE TITLE
More number types

### ISSUE THREAD

**Issue by evaera** [evaera/Cmdr#69]
`natural`, which would be a subset of the current `integer` type, would allow numbers in the range `0..n`.
`positive`, which would be a subset of `natural`, would allow the range `1..n`

`byte`, which would allow the range `0..255`.
`digit`, which would allow the range `0..9`.

**Comment by LoganDark** [comment]
What about negative variants of these types?

You could have `negative` (`n..-1`), `zero` (`0`), and `positive` (`1..n`)?

**Comment by evaera** [comment]
What's the use case for `zero`? And if you're only going to allow `negative`, I think you might as well just use `positive` and then negate it in the command.

Generic types would be nice but are currently an unsupported feature.

**Comment by LoganDark** [comment]
@evaera Can't you combine types? I think I've seen it in the teleport command, although I suspect the `@` just says "if you see an @ just use this other type"...

**Comment by evaera** [comment]
Those are [Prefixed Union Types](https://github.com/evaera/Cmdr#prefixed-union-types). Actual union types might be too complex to support in this version of Cmdr.

**Comment by LoganDark** [comment]
Maybe negative, not_negative (positive and 0), and positive and not_positive (negative and 0)?
