### ISSUE TITLE
Add "Tab→" note on autocompletion entries

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#70]
Imagine this:

Type `h`. You see `help`, but you want `history`. Down arrow to select `history`, review the description, looks good. Right arrow... doesn't autocomplete, nothing happens. That's okay... clicking on the item also does nothing... Well heck, now I have to type a whole 5 letters. This is definitely not okay.

:)

**Comment by evaera** [comment]
You should press Tab to auto-complete, not right arrow. Perhaps right arrow could be added as an alternative in addition to Tab.

**Comment by LoganDark** [comment]
And don't forget clicking on the item directly. I got extremely confused when even that didn't work.

**Comment by evaera** [comment]
I'm not too sure on the clicking, since Cmdr is solely a keyboard experience right now. I think I'd rather hold off on making them buttons until if/when Cmdr receives an update to make it compatible with touch interfaces.

**Comment by LoganDark** [comment]
I wasn't implying for it to not be a keyboard experience, however some kind of footnote or right-arrow completion (as my actual shell supports) would be nice.

**Comment by evaera** [comment]
Actually, I don't think it would be possible to support right-arrow completion since there is no way to determine what the user's cursor position is inside a TextBox at any given moment. Thus it would be impossible to distinguish if the user was auto-completing or just moving their cursor to the right.

**Comment by LoganDark** [comment]
Footnote then?

**Comment by evaera** [comment]
Sure, I imagine it looking like this: (without the outline...)
![image](https://user-images.githubusercontent.com/2489210/52909722-18bd9080-325b-11e9-879f-c099be473658.png)

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/52909746-4518e300-3242-11e9-8b48-16f575a6b525.png)

IMHO this would work better.

**Comment by LoganDark** [comment]
Here's a graphic, if you'd like.

![slice](https://user-images.githubusercontent.com/4723091/52909770-a5a82000-3242-11e9-9051-11312f7f4071.png)

**Comment by evaera** [comment]
Note that it's now possible to add support for right arrow completion, as the [`CursorPosition`](https://developer.roblox.com/api-reference/property/TextBox/CursorPosition) property has been added to text boxes.

**Comment by LoganDark** [comment]
Yeeeeeeeesssssssss!
