### ISSUE TITLE
Type information is misaligned on Retina displays

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#71]
![image](https://user-images.githubusercontent.com/4723091/52909693-9f657400-3241-11e9-8731-b598eb245e96.png)

In my game's version I've set the size of the type info to the same size as the argument name:

![image](https://user-images.githubusercontent.com/4723091/52909708-d9367a80-3241-11e9-800e-0082435158c0.png)

Unfortunately I know of no fix. This is an issue on Roblox's side. Text rendering on Retina displays is dodgy at best right now.

**Comment by evaera** [comment]
Yeah, I don't think this is fixable unfortunately without disturbing the alignment on lower-resolution displays.
