### ISSUE TITLE
Empty quotes don't trigger validation?

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#72]
![image](https://user-images.githubusercontent.com/4723091/52910291-33d3d480-324a-11e9-9bc0-5f2b9da5d410.png)

These are two single quotes.

Shouldn't it validate if the 'string' is closed? I understand it not erroring immediately if you just typed the opening quote, but this (closing quote and all) _can_ be sent to the server and you'll get a "An error occurred while running this command."

Additionally, these are optional arguments. IMHO, an empty string should _skip_ optional arguments, right?

**Comment by evaera** [comment]
I think this is because the `Default` is being replaced with `nil`. Does that align with what you're seeing here?

**Comment by LoganDark** [comment]
@evaera these are optional arguments with a default. The server validates the empty string to check if it's a boolean and says no.

![image](https://user-images.githubusercontent.com/4723091/52910391-b01ae780-324b-11e9-800a-b3b0a0948105.png)

**Comment by LoganDark** [comment]
Ty
