### ISSUE TITLE
Subcommands

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#73]
I have this car I'd like to be configurable through Cmdr.

Right now, I have this one command, `carconfig` which accepts 7 arguments, ranging from things like the antigravity to the camera settings to the ride height to the suspension stiffness and so on.

I'd rather be able to have multiple commands, like `car info`, `car rideheight 2` or something, each with their own autocomplete, but grouped under one prefix (`car`). `info` and `rideheight` would just be subcommands of `car` in that case, if it makes any sense. When typing `car` it would autocomplete the subcommands.

**Comment by evaera** [comment]
Is this fundamentally different from just using a prefix like `car_` and making multiple commands? (Which is what I'd recommend)

**Comment by LoganDark** [comment]
No, actually, it's not really that different. I suppose the space just makes it nicer. Realizing how trivial this is, feel free to close the issue if it'll be too much of a pain to implement.

**Comment by evaera** [comment]
Technically, command names can have spaces in them as well. I think the tab auto completion is broken for this (doesn't automatically wrap in quotes like it does for arguments with spaces in them), but if you manually include the quotation marks it will work as expected. 

![image](https://user-images.githubusercontent.com/2489210/52912670-9648c700-3282-11e9-8510-6a8a229b8c0f.png)

**Comment by evaera** [comment]
@LoganDark Also, feel free to add me on Discord if you want to talk about features more easily there: eryn#0001

**Comment by LoganDark** [comment]
I think I prefer the underscore over the weird quoted behavior of commands with spaces in them.
