### ISSUE TITLE
Different "modes"

### ISSUE THREAD

**Issue by LoganDark** [evaera/Cmdr#75]
Related to #74 and #67

---

What if you could enter a command that changes the commands you can run? Perhaps instead of multiple GUIs you could use a command to 'switch' Cmdr to another set of commands. For example, `enter_admin` to switch from user mode to admin mode and `exit_admin` to switch back to user mode... This is all a concept, of course

**Comment by evaera** [comment]
I think this would already be possible when #67 is implemented. You could make your own command that updates some global state about what commands are active, and then check that in your hook. If you interrupt those commands from showing up they won't be runnable by the user.
