### ISSUE TITLE
Enable mouse on activation

### ISSUE THREAD

**Issue by ryan-c-scott** [evaera/Cmdr#81]
We lock our mouse, so we can't scroll the console when we bring it up.
Would be nice to have it automatically enable the mouse and put it back to its previous state on deactivation.

**Comment by LoganDark** [comment]
For now you can show/hide the console manually and handle that logic yourself.

Note: I'm not saying to do that instead, I'm just letting you know what you can do until a feature like this is implemented.

**Comment by ryan-c-scott** [comment]
It's a good point.  Overall it's an extremely minor feature request and not bad to work around.

**Comment by LoganDark** [comment]
Yeah, after all you're the one locking the mouse, but I digress. Cmdr already grabs keyboard input, so I believe it would be good to ensure the mouse is usable as well. The APIs for showing and hiding Cmdr aren't that well documented either, either that or they don't exist, I don't remember which (from when I tried doing that manually).
