### ISSUE TITLE
Clicking outside of the command bar should close the command bar

### ISSUE THREAD

**Issue by Nimblz** [evaera/Cmdr#96]
Clicking outside of the command bar or otherwise losing focus on the command bar input should hide the bar as if the user pressed the close hotkey. Currently you have to press the toggle key to close the bar which can be a bit clunky if you only want to run one command quickly.

**Comment by evaera** [comment]
I think current behavior might be desirable for some people, but I'm willing to have this as optional (maybe default) behavior

**Comment by TsjipTsjip** [comment]
I've drafted something that could achieve this. Draft PR is linked [here](https://github.com/evaera/Cmdr/pull/129).
